---

name: Packer

on:
  push:
# on:
#   release:
#     types: [created]

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      # - name: Fix Template
      #   uses: operatehappy/packer-github-actions@master
      #   with:
      #     command: fix

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./cloud/aws/ami/ubuntu/20.04/packer.json

      # build artifact
      - name: Build Artifact
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ./cloud/aws/ami/ubuntu/20.04/packer.json

      # additional steps to process artifacts